### PR TITLE
Add assetfolder to contain textures & fonts + a free use/distribute font

### PR DESCRIPTION
**Pull request by Moar-Chan**
I think we should use a asset folder to contain multiple types of data.

### CODE REVIEW

**Comment by Moar-Chan** [comment]
The font is from https://fontlibrary.org/en/font/fantasque-sans-mono
it is under OFL (SIL Open Font License)

**Comment by Moar-Chan** [comment]
Just to clarify this is so we can add ttf examples in the future

**Comment by lcnr** [comment]
I don't feel comfortable with adding a font to this repository before we actually use it.

And while having an asset folder is great once we have other assets, I don't think that doing it before this is a good change.

**Comment by Moar-Chan** [comment]
Understood

**Pull request closed without merging**
